version: '3.7'

networks:
    A1:
        driver: bridge

services:
### Applications Code Container #############################
    applications:
        image: tianon/true
        volumes: &AppVol
          - type: bind
            source: ./src/
            target: /usr/src/app
          - type: bind
            source: ./tmp/logs
            target: /var/log/nginx
          - type: bind
            source: ./config/nginx/nginx.conf
            target: /etc/nginx/nginx.conf
          - type: bind
            source: ./config/${ENVIRONMENT}.conf
            target: /etc/nginx/conf.d/site.conf
          - type: bind
            source: ${SSL_CERT_PATH}
            target: /etc/ssl/certs/cert.pem
          - type: bind
            source: ${SSL_CERT_KEY_PATH}
            target: /etc/ssl/key.pem
          - type: bind
            source: ${SSL_CERT_CLOUDFLARE}
            target: /etc/ssl/cloudflare.crt
          - type: bind
            source: ${SSL_CERT_DHPARAM}
            target: /etc/ssl/dhparam4096.pem
        container_name: nuxt-app
        networks:
            - A1

### nginx container ###############
    nginx:
        build: ./dockers/nginx/
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
            - 443
        links:
            - nuxtjs
        volumes: *AppVol

        container_name: nuxt-nginx
        networks:
            - A1

### NuxtJS frontend Container #############################
    nuxtjs:
        build:
            context: ./src/
        volumes: *AppVol
        ports:
            - 3000:3000
        container_name: nuxt-js
        command: ["yarn", "production"]
        networks:
            - A1