version: '3.8'

services:
    nginx:
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Dynasty-Build-03/:/Dynasty/A1/
            - ./Ailo/:/a1/
            - ./logs:/var/log/nginx
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./Djin/ssl.conf:/etc/nginx/Djin/ssl.conf
            - ./Djin/mime.types:/etc/nginx/Djin/mime.types
            - ./config/${ENVIRONMENT}.conf:/etc/nginx/conf.d/site.conf
            - ${SSL_CERT_PATH}:/etc/nginx/certs/cert.pem
            - ${SSL_CERT_KEY_PATH}:/etc/nginx/certs/key.pem
            - ${SSL_DHPARAM}:/etc/nginx/certs/dhparam4096.pem
        container_name: nginx-framework
        restart: always
        networks:
            - SUN

    nuxt:
        build:
            context: ./Ailo
            dockerfile: Dockerfile
        volumes:
            - ./Ailo/:/a1/
        expose:
            - 3264
        environment: 
            HOST: 0.0.0.0
        container_name: nuxt
        command: ["yarn", "buildProd"]
        networks:
            - SUN

    dynasty:
        build:
            context: ./Dynasty-Build-03/
            dockerfile: Dockerfile
        volumes:
            - ./Dynasty-Build-03/:/Dynasty/A1/
        expose:
            - 3000
        container_name: dynasty-production
        command: ["yarn", "modern"]
        networks:
            - SUN
        
networks:
    SUN:
        driver: bridge