version: '3.7'

networks:
    A1:
       driver: bridge #Review 
       
services:
    nginx:
        build: ./dockers/nginx/
        ports:
            - 80:80
            - 443:443
        links:
            - nuxtjs
        volumes:
            - ./src/:/Applications/A1/
            - ./tmp/logs:/var/log/nginx
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./Djin/ssl.conf:/etc/nginx/Djin/ssl.conf
            - ./Djin/headers.conf:/etc/nginx/Djin/headers.conf
            - ./config/${ENVIRONMENT}.conf:/etc/nginx/conf.d/site.conf
            - ${SSL_CERT_PATH}:/etc/nginx/certs/cert.pem
            - ${SSL_CERT_KEY_PATH}:/etc/nginx/certs/key.pem
            # - ${SSL_TRUSTED_CERTIFICATE}:/etc/nginx/certs/cloudflare.crt
            - ${SSL_DHPARAM}:/etc/nginx/certs/dhparam4096.pem
            - ./Djin/mime.types:/etc/nginx/Djin/mime.types
        container_name: nuxt-nginx-prod
        networks:
            - A1
    nuxtjs:
        build:
            context: ./src/
            dockerfile: Dockerfile
        volumes:
            - ./src/:/Applications/A1/
        expose:
            - 3000
        container_name: nuxt-js-prod
        command: ["yarn", "production"]
        networks:
            - A1