version: '3.7'

networks:
    A1:
       driver: bridge

services:
# Applications Code Container 
    applications:
        image: tianon/true
        volumes: &AppVol
        - ./src/:/usr/src/app
        - ./tmp/logs:/var/log/nginx
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./config/${ENVIRONMENT}.conf:/etc/nginx/conf.d/site.conf
        - ${SSL_CERT_PATH}:/etc/ssl/certs/cert.pem
        - ${SSL_CERT_KEY_PATH}:/etc/ssl/certs/key.pem
        - ${SSL_CLIENT_CERTIFICATE}:/etc/ssl/certs/cloudflare.crt
        - ${SSL_DHPARAM}:/etc/ssl/certs/dhparam4096.pema
        container_name: nuxt-app-prod
        networks:
            - A1

# nginx container
    nginx:
        build: ./dockers/nginx/
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
            - 443
        links:
            - nuxtjs
        volumes: *AppVol
        container_name: nuxt-nginx-prod
        networks:
            - A1

# NuxtJS frontend Container
    nuxtjs:
        build:
            context: ./src/
        volumes: *AppVol
        ports:
            - 3000:3000
        container_name: nuxt-js-prod
        command: ["yarn", "production"]
        networks:
            - A1