version: '3.7'

services:
    nginx:
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Dynasty-Build-03/:/Dynasty/A1/
            - ./Ailo/:/de/
            - ./logs:/var/log/nginx
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./Djin/ssl.conf:/etc/nginx/Djin/ssl.conf
            - ./Djin/mime.types:/etc/nginx/Djin/mime.types
            - ./config/${ENVIRONMENT}.conf:/etc/nginx/conf.d/site.conf
            - ${SSL_CERT_PATH}:/etc/nginx/certs/cert.pem
            - ${SSL_CERT_KEY_PATH}:/etc/nginx/certs/key.pem
            - ${SSL_DHPARAM}:/etc/nginx/certs/dhparam4096.pem #change paths to /etc/ssl/private/key.pem | /etc/ssl/certs/cert.pem ?
        container_name: nginx-framework
        restart: always
        logging:
            driver: "json-file"
            options:
              max-size: "200k"
              max-file: "10"
        networks:
            - SUN

    nuxt:
        build:
            context: ./Ailo
            dockerfile: Dockerfile
        volumes:
            - ./Ailo/:/de/
        expose:
            - 3001
        container_name: nuxt
        command: ["yarn", "buildProd"]
        networks:
            - SUN

    dynasty:
        build:
            context: ./Dynasty-Build-03/
            dockerfile: Dockerfile
        volumes:
            - ./Dynasty-Build-03/:/Dynasty/A1/
        expose:
            - 3000
        container_name: dynasty-production
        command: ["yarn", "modern"]
        networks:
            - SUN
        
networks:
    SUN:
        driver: bridge